[package]
name = "rnprefix"
version = "1.0.0"
authors = ["Genny Z <gen@nyble.dev>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
